const menu = [
  {
    id: 1,
    title: "Panqueca",
    category: "café da manhã",
    price: 15.99,
    img: "./images/item-1.jpeg",
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec commodo dolor eget lacus pellentesque, id pretium leo pulvinar. Sed ut porta dolor, ut imperdiet nisi. Suspendisse id dapibus odio.`,
  },
  {
    id: 2,
    title: "jantar duplo",
    category: "almoço",
    price: 13.99,
    img: "./images/item-2.jpeg",
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec commodo dolor eget lacus pellentesque, id pretium leo pulvinar. Sed ut porta dolor, ut imperdiet nisi. Suspendisse id dapibus odio.`,
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "shakes",
    price: 6.99,
    img: "./images/item-3.jpeg",
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec commodo dolor eget lacus pellentesque, id pretium leo pulvinar. Sed ut porta dolor, ut imperdiet nisi. Suspendisse id dapibus odio.`,
  },
  {
    id: 4,
    title: "a moda da casa",
    category: "café da manhã",
    price: 20.99,
    img: "./images/item-4.jpeg",
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec commodo dolor eget lacus pellentesque, id pretium leo pulvinar. Sed ut porta dolor, ut imperdiet nisi. Suspendisse id dapibus odio.`,
  },
  {
    id: 5,
    title: "ovos mechidos",
    category: "almoço",
    price: 22.99,
    img: "./images/item-5.jpeg",
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec commodo dolor eget lacus pellentesque, id pretium leo pulvinar. Sed ut porta dolor, ut imperdiet nisi. Suspendisse id dapibus odio.`,
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 18.99,
    img: "./images/item-6.jpeg",
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec commodo dolor eget lacus pellentesque, id pretium leo pulvinar. Sed ut porta dolor, ut imperdiet nisi. Suspendisse id dapibus odio.`,
  },
  {
    id: 7,
    title: "bacon",
    category: "café da manhã",
    price: 8.99,
    img: "./images/item-7.jpeg",
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec commodo dolor eget lacus pellentesque, id pretium leo pulvinar. Sed ut porta dolor, ut imperdiet nisi. Suspendisse id dapibus odio.`,
  },
  {
    id: 8,
    title: "clássico",
    category: "almoço",
    price: 12.99,
    img: "./images/item-8.jpeg",
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec commodo dolor eget lacus pellentesque, id pretium leo pulvinar. Sed ut porta dolor, ut imperdiet nisi. Suspendisse id dapibus odio.`,
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "shakes",
    price: 16.99,
    img: "./images/item-9.jpeg",
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec commodo dolor eget lacus pellentesque, id pretium leo pulvinar. Sed ut porta dolor, ut imperdiet nisi. Suspendisse id dapibus odio.`,
  },
];
export default menu;
